
# ici on defini ou se trouve gunicorn et on donne un nom, ici "django"
upstream django {
    server web:8000;
        }

# bloc general ===================================================================================

server {
    
    # la machine est le server donc on ecoute sur le port http : le 80
    listen 80;

    # taille max pour une photo par exemple
    client_max_body_size 20M;


    # on setup les requetes precise : quand une requete commence par /static/ fait ca etc 
    location /static/ {
        alias /app/staticfiles/;
        }

    location /media/ {
        alias /app/media/;
        }
    
    # ici : pour tout autre requete on passe la main gunicorn
    location / {
        proxy_pass http://django;
        # explique que le call vient de nginx fiable :
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        }
}

